const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("quill", {
  getBootstrap: () => ipcRenderer.invoke("get-bootstrap"),
  saveState: (state) => ipcRenderer.invoke("save-state", state),
  getEnv: () => ipcRenderer.invoke("get-env"),
  saveEnvKeys: (updates) => ipcRenderer.invoke("save-env-keys", updates),
  getMcpConfig: (cwd) => ipcRenderer.invoke("get-mcp-config", cwd),
  saveMcpConfig: (cwd, config) => ipcRenderer.invoke("save-mcp-config", { cwd, config }),
  reloadMcpAgents: (cwd) => ipcRenderer.invoke("reload-mcp-agents", cwd),
  saveWorkspaceProfile: (ws) => ipcRenderer.invoke("save-workspace-profile", ws),
  importWorkspaceFile: (filePath) => ipcRenderer.invoke("import-workspace-file", filePath),
  pickFolder: () => ipcRenderer.invoke("pick-folder"),
  pickWorkspaceFile: () => ipcRenderer.invoke("pick-workspace-file"),
  ptyCreate: (opts) => ipcRenderer.invoke("pty-create", opts),
  ptyWrite: (id, data) => ipcRenderer.invoke("pty-write", { id, data }),
  ptyResize: (id, cols, rows) => ipcRenderer.invoke("pty-resize", { id, cols, rows }),
  ptyKill: (id) => ipcRenderer.invoke("pty-kill", { id }),
  onPtyData: (cb) => ipcRenderer.on("pty-data", (_e, payload) => cb(payload)),
  onPtyExit: (cb) => ipcRenderer.on("pty-exit", (_e, payload) => cb(payload)),
  onWorkspaceFileChanged: (cb) => ipcRenderer.on("workspace-file-changed", (_e, payload) => cb(payload)),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  quit: () => ipcRenderer.invoke("app-quit"),
  getGitInfo: (cwd) => ipcRenderer.invoke("get-git-info", cwd),
  gitBranches: (cwd) => ipcRenderer.invoke("git-branches", cwd),
  gitCheckout: (opts) => ipcRenderer.invoke("git-checkout", opts),
  gitStage: (opts) => ipcRenderer.invoke("git-stage", opts),
  gitCommit: (opts) => ipcRenderer.invoke("git-commit", opts),
  gitStatusFiles: (cwd) => ipcRenderer.invoke("git-status-files", cwd),
  listDirectory: (dirPath) => ipcRenderer.invoke("list-directory", dirPath),
  readFile: (filePath) => ipcRenderer.invoke("read-file", filePath),
  writeFile: (opts) => ipcRenderer.invoke("write-file", opts),
  gitShowFile: (opts) => ipcRenderer.invoke("git-show-file", opts),
  gitDiff: (opts) => ipcRenderer.invoke("git-diff", opts),
  searchFiles: (opts) => ipcRenderer.invoke("search-files", opts),
  testMcpServer: (spec) => ipcRenderer.invoke("test-mcp-server", spec),
  checkForUpdates: () => ipcRenderer.invoke("check-for-updates"),
  searchContent: (opts) => ipcRenderer.invoke("search-content", opts),
  listSymbols: (opts) => ipcRenderer.invoke("list-symbols", opts),
  gitFileGutter: (opts) => ipcRenderer.invoke("git-file-gutter", opts),
  gitRevertFile: (opts) => ipcRenderer.invoke("git-revert-file", opts),
  getKeybindings: () => ipcRenderer.invoke("get-keybindings"),
  saveKeybindings: (bindings) => ipcRenderer.invoke("save-keybindings", bindings),
  exportWorkspaceSync: (state) => ipcRenderer.invoke("export-workspace-sync", state),
  importWorkspaceSync: () => ipcRenderer.invoke("import-workspace-sync"),
  getProvider: () => ipcRenderer.invoke("get-provider"),
  setProvider: (provider) => ipcRenderer.invoke("set-provider", provider),
  getTasks: (cwd) => ipcRenderer.invoke("get-tasks", cwd),
  saveTasks: (opts) => ipcRenderer.invoke("save-tasks", opts),
  getDroppedPath: (file) => {
    try { return webUtils?.getPathForFile?.(file) || file?.path || ""; }
    catch { return file?.path || ""; }
  },
  statPath: (p) => ipcRenderer.invoke("stat-path", p),
});
